//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1N2WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> timeSignedIn { get; set; }
        public Nullable<System.DateTime> dateSignedIn { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
