//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G1N2WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassOccurance
    {
        public int Barcode { get; set; }
        public int ClassID { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
